### PR TITLE
3 color scheme

### LINKED ISSUE #3: Refactor the color scheme
It feels like the template colors are everywhere in the css, directly in the svgs ... magic numbers everywhere.

## Todo
- find a new color config file json/css.. whatever fits to be put into `match4everyone/config`
- with 2-5 base colors that are sparsely used EVERYWHERE to emphasise the two participants
- and try to integrate them into existing templates (especially map, home)

## Resources
- [Color schemes with five colors ](https://color.adobe.com/search?q=dual)

image

### PR DESCRIPTION
**Pull request by bjrne**
Works towards #3 

Changes:
- correctly compile and include scss files with variables
- use scss variables for all hardcoded style colors, apart from background colors and inline style blocks
- replace `btn blue` with `btn btn-primary`

TODO in next PRs:
- styles aus htmls raus
- nach rgba suchen und ggf ersetzen durch vars
- wie machen wir Farben in `password_set_email.html` modular
- unify slightly varying background colors and use scss vars
- clean css structure further

### CODE REVIEW

**Comment by bjrne** [comment]
Since this will be a huge chance in the end, lets divide this into several PRs in order to enable better review, faster merges and less merge conflicts :tada:

**Comment by feeds** [comment]
A lot of blue to primary ... should only malte review this?

**Comment by bjrne** [comment]
Noooo, please go ahead :) I did the structural changes together with Malte yesterday, so even better if someone else reviews this :) 

For minor technicalities regarding css, there will be many possibilities to correct in future PRs.

**Comment by feeds** [comment]
image
Here I still see the old colors (set in map.js)

**Review by feeds — APPROVED** [review]
If that is fixed, please merge :)

**Comment by feeds** [comment]
image
Good that I know where to click ;)

**Comment by bjrne** [comment]
Invisible buttons were a cache issue, map legend icons will be changed in next PRs.

**Pull request merged**
