### PR TITLE
Remove p_type from urls that do not need it

### LINKED ISSUE #148: Remove p_type from deletion routes and activation routes
Depends on #105  and #126

### PR DESCRIPTION
**Pull request by bjrne**
Closes #148.

### CODE REVIEW

**Comment by Baschdl** [comment]
Do they really don't need it? Did you think about use cases where one wants to display different pages? Maybe to note that one deletion has more effects than another (e.g. "No candidates are able to contact you", "You will not be able to communicate with any members of our platform")

**Comment by feeds** [comment]
I think in the cases you mentioned @Baschdl  one can still retrieve the information about the participant from the active user. So since no other user but yourself should be able to 'delete_me' its generally fine.

Only issue could be editing with django cms. But I would go for it as @bjrne proposed.

**Comment by feeds** [comment]
I think in the cases you mentioned @Baschdl  one can still retrieve the information about the participant from the active user. So since no other user but yourself should be able to 'delete_me' its generally fine.

Only issue could be editing with django cms. But I would go for it as @bjrne proposed.

**Comment by Baschdl** [comment]
We don't intend right now to make pages other than home, about, imprint etc. editable

**Comment by feeds** [comment]
then this change is just what we want

**Review by Baschdl — APPROVED** [review]
Works and looks fine

**Pull request merged**
